import { useEffect, useState } from 'react';
import api, { type DeliveryAreaRecord, type DiscountCodeRecord } from '../lib/api';
import './settings.css';

const money = (value: number) => `₦${value.toLocaleString('en-NG')}`;
export default function CheckoutManagement() {
  const [areas, setAreas] = useState<DeliveryAreaRecord[]>([]); const [codes, setCodes] = useState<DiscountCodeRecord[]>([]); const [name, setName] = useState(''); const [fee, setFee] = useState(''); const [code, setCode] = useState(''); const [type, setType] = useState<'percent' | 'fixed'>('percent'); const [value, setValue] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  async function load() { try { const [a, c] = await Promise.all([api.get('/api/checkout-config/delivery-areas/admin'), api.get('/api/checkout-config/discount-codes')]); setAreas(a.data.items); setCodes(c.data.items); } catch { setError('Could not load checkout settings.'); } }
  useEffect(() => { void load(); }, []);
  async function addArea(event: React.FormEvent) { event.preventDefault(); setError(''); try { await api.post('/api/checkout-config/delivery-areas', { name, fee: Number(fee) }); setName(''); setFee(''); setNotice('Delivery area added.'); await load(); } catch (err: any) { setError(err.response?.data?.error || 'Could not add delivery area.'); } }
  async function addCode(event: React.FormEvent) { event.preventDefault(); setError(''); try { await api.post('/api/checkout-config/discount-codes', { code, type, value: Number(value) }); setCode(''); setValue(''); setNotice('Discount code added.'); await load(); } catch (err: any) { setError(err.response?.data?.error || 'Could not add discount code.'); } }
  async function toggleArea(area: DeliveryAreaRecord) { await api.put(`/api/checkout-config/delivery-areas/${area._id}`, { active: !area.active }); await load(); }
  async function toggleCode(item: DiscountCodeRecord) { await api.put(`/api/checkout-config/discount-codes/${item._id}`, { active: !item.active }); await load(); }
  return <div className="settings-page"><div className="settings-page__head"><div><div className="admin-page__eyebrow">Checkout / controls</div><h2>Delivery & discounts <em>with clarity.</em></h2><p className="settings-page__intro">These values feed the public checkout and are snapshotted onto each order at placement.</p></div></div>{error && <p className="settings-message settings-message--error" role="alert">{error}</p>}{notice && <p className="settings-message" role="status">{notice}</p>}<div className="settings-page__grid"><section className="settings-card"><div className="settings-card__eyebrow">Delivery areas</div><h3>Where we deliver.</h3><form className="settings-form" onSubmit={addArea}><label>Area name<input value={name} onChange={(e) => setName(e.target.value)} required placeholder="Old Market Axis" /></label><label>Fee<input value={fee} onChange={(e) => setFee(e.target.value)} required type="number" min="0" inputMode="numeric" placeholder="500" /></label><button type="submit">Add area ↗</button></form><div className="settings-list">{areas.map((area) => <div className="settings-list__row" key={area._id}><span>{area.name}<small>{money(area.fee)}</small></span><button className="settings-support" type="button" onClick={() => void toggleArea(area)}>{area.active ? 'Deactivate' : 'Reactivate'}</button></div>)}</div></section><section className="settings-card"><div className="settings-card__eyebrow">Discount codes</div><h3>Reward regulars.</h3><form className="settings-form" onSubmit={addCode}><label>Code<input value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} required placeholder="WELCOME10" /></label><label>Type<select value={type} onChange={(e) => setType(e.target.value as 'percent' | 'fixed')}><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></label><label>Value<input value={value} onChange={(e) => setValue(e.target.value)} required type="number" min="0.01" step="0.01" /></label><button type="submit">Add code ↗</button></form><div className="settings-list">{codes.map((item) => <div className="settings-list__row" key={item._id}><span>{item.code}<small>{item.type === 'percent' ? `${item.value}%` : money(item.value)} · used {item.usedCount}</small></span><button className="settings-support" type="button" onClick={() => void toggleCode(item)}>{item.active ? 'Deactivate' : 'Reactivate'}</button></div>)}</div></section></div></div>;
}
