/* Gallery workspace: archive-first content safety with high-clarity mobile controls and purposeful editorial card layout. */
import { useCallback, useEffect, useState } from 'react';
import api from '../lib/api';
import ConfirmDialog from '../components/ConfirmDialog';
import ImageUploadField from '../components/ImageUploadField';
import '../styles/gallery-manager.css';

interface GalleryImage { _id: string; imageUrl: string; caption?: string; category: string; archivedAt?: string; }
type Scope = 'active' | 'archived'; type ArchiveAction = 'archive' | 'restore' | 'delete'; type PendingAction = { image: GalleryImage; action: ArchiveAction };
const emptyForm = { imageUrl: '', caption: '', category: '' }; type GalleryFormErrors = Partial<Record<'imageUrl' | 'category', string>>;
function dialogCopy(action: ArchiveAction) { return action === 'archive' ? { title: 'Move image to Archive?', message: 'It will leave the public gallery but stay recoverable in Archive. You can restore it at any time.', label: 'Archive image', busy: 'Archiving…' } : action === 'restore' ? { title: 'Restore this gallery image?', message: 'The image will return to the active public gallery.', label: 'Restore image', busy: 'Restoring…' } : { title: 'Permanently delete this gallery image?', message: 'This archived image and its saved details will be permanently removed. This cannot be undone.', label: 'Delete permanently', busy: 'Deleting…' }; }
function formatArchiveDate(value?: string) { return value ? new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Africa/Lagos' }).format(new Date(value)) : ''; }

export default function GalleryManager() {
  const [scope, setScope] = useState<Scope>('active'); const [images, setImages] = useState<GalleryImage[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState<string | null>(null); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [loadFailed, setLoadFailed] = useState(false); const [formErrors, setFormErrors] = useState<GalleryFormErrors>({}); const [pendingAction, setPendingAction] = useState<PendingAction | null>(null); const [actionId, setActionId] = useState<string | null>(null);
  const fetchImages = useCallback(async () => { setLoading(true); setLoadFailed(false); try { const res = await api.get('/api/gallery/admin', { params: { scope } }); setImages(res.data.images); } catch { setError('Could not load gallery images.'); setLoadFailed(true); } finally { setLoading(false); } }, [scope]);
  useEffect(() => { const timer = window.setTimeout(() => { void fetchImages(); }, 0); return () => window.clearTimeout(timer); }, [fetchImages]);
  function chooseScope(nextScope: Scope) { setScope(nextScope); setShowForm(false); setError(''); }
  function openCreateForm() { setForm(emptyForm); setFormErrors({}); setEditingId(null); setShowForm(true); }
  function openEditForm(image: GalleryImage) { setForm({ imageUrl: image.imageUrl, caption: image.caption || '', category: image.category }); setFormErrors({}); setEditingId(image._id); setShowForm(true); }
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); const nextErrors: GalleryFormErrors = {}; if (!form.imageUrl.trim()) nextErrors.imageUrl = 'Upload an image before saving this gallery item.'; if (!form.category.trim()) nextErrors.category = 'Add a category so the gallery can be filtered.'; if (Object.keys(nextErrors).length) { setFormErrors(nextErrors); return; } setSaving(true); setError(''); setFormErrors({}); try { if (editingId) await api.put(`/api/gallery/${editingId}`, form); else await api.post('/api/gallery', form); setShowForm(false); await fetchImages(); } catch { setError('Something went wrong saving this image.'); } finally { setSaving(false); } }
  async function confirmAction() { if (!pendingAction) return; const { image, action } = pendingAction; setActionId(image._id); setError(''); try { if (action === 'delete') await api.delete(`/api/gallery/${image._id}`); else await api.post(`/api/gallery/${image._id}/${action}`); setPendingAction(null); await fetchImages(); } catch { setError(`Something went wrong ${action === 'delete' ? 'permanently deleting' : `${action}ing`} this image.`); } finally { setActionId(null); } }
  const dialog = pendingAction ? dialogCopy(pendingAction.action) : null;
  const activeCopy = scope === 'active';
  return <div className="gallery-manager">
    <section className="gallery-manager__head"><div><div className="gallery-manager__eyebrow">Media library / gallery</div><h2>Gallery <em>control.</em></h2><p>{activeCopy ? 'Keep the public gallery intentional. Archive removes an image from view while keeping it recoverable.' : 'Review stored images here. Restore sends an image back to the public gallery; permanent deletion stays deliberately separate.'}</p></div>{activeCopy && <button type="button" onClick={openCreateForm} className="gallery-manager__add">Add image <span aria-hidden="true">+</span></button>}</section>
    <section className="gallery-manager__lifecycle" aria-label="Gallery image lifecycle">
      <div className="gallery-manager__lifecycle-copy"><span>{activeCopy ? 'Step 1 of 2' : 'Step 2 of 2'}</span><strong>{activeCopy ? 'Archive first. Delete only from Archive.' : 'Restore or permanently delete archived images.'}</strong><small>{activeCopy ? 'This protects your public gallery from accidental permanent loss.' : 'Permanent delete is irreversible and is always confirmed.'}</small></div>
      <div className="gallery-manager__tabs" role="tablist" aria-label="Gallery catalog view"><button type="button" role="tab" aria-selected={scope === 'active'} onClick={() => chooseScope('active')} className={scope === 'active' ? 'is-active' : ''}>Active <span>Public</span></button><button type="button" role="tab" aria-selected={scope === 'archived'} onClick={() => chooseScope('archived')} className={scope === 'archived' ? 'is-active' : ''}>Archive <span>Restore / delete</span></button></div>
    </section>
    {error && <div className="gallery-manager__alert" role="alert"><span>{error}</span>{loadFailed && <button type="button" onClick={() => void fetchImages()}>Retry loading</button>}</div>}
    {showForm && <form onSubmit={handleSubmit} noValidate className="gallery-manager__form"><div><span>Image record</span><h3>{editingId ? 'Edit gallery image' : 'Add to public gallery'}</h3><p>Save the visual and its category together so the gallery stays easy to browse.</p></div><ImageUploadField value={form.imageUrl} onChange={(url) => setForm({ ...form, imageUrl: url })} />{formErrors.imageUrl && <p className="gallery-manager__field-error" role="alert">{formErrors.imageUrl}</p>}<div className="gallery-manager__form-grid"><label htmlFor="gallery-category">Category<input id="gallery-category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} placeholder="Plated, Events, Kitchen…" aria-invalid={Boolean(formErrors.category)} aria-describedby={formErrors.category ? 'gallery-category-error' : undefined} /></label><label htmlFor="gallery-caption">Caption <em>optional</em><input id="gallery-caption" value={form.caption} onChange={(e) => setForm({ ...form, caption: e.target.value })} placeholder="A concise public description" /></label></div>{formErrors.category && <p id="gallery-category-error" className="gallery-manager__field-error">{formErrors.category}</p>}<div className="gallery-manager__form-actions"><button type="submit" disabled={saving} className="gallery-manager__save">{saving ? 'Saving…' : editingId ? 'Save changes' : 'Save image'}</button><button type="button" onClick={() => setShowForm(false)} className="gallery-manager__cancel">Cancel</button></div></form>}
    <div className="gallery-manager__catalog-head"><div><span>{activeCopy ? 'Active gallery' : 'Archive bin'}</span><strong>{loading ? 'Loading images…' : `${images.length} ${images.length === 1 ? 'image' : 'images'}`}</strong></div>{activeCopy ? <p>To permanently remove an image, move it to Archive first.</p> : <p>Only archived images show the permanent Delete action.</p>}</div>
    {loading ? <div className="gallery-manager__empty">Loading gallery images…</div> : images.length === 0 ? <div className="gallery-manager__empty"><strong>{scope === 'archived' ? 'Your Archive is clear.' : 'Your gallery is ready for its first image.'}</strong><span>{scope === 'archived' ? 'Archived images will appear here with Restore and permanent Delete controls.' : 'Use Add image to create a new public gallery record.'}</span>{scope === 'active' && <button type="button" onClick={openCreateForm}>Add image</button>}</div> : <div className="gallery-manager__grid">{images.map((image) => <article key={image._id} className="gallery-manager__card"><div className="gallery-manager__image-wrap"><img src={image.imageUrl} alt={image.caption || image.category} /><span>{image.category}</span>{scope === 'archived' && <b>Archived</b>}</div><div className="gallery-manager__card-body"><div className="gallery-manager__card-copy"><small>{image.category}</small><h3>{image.caption || 'Untitled gallery image'}</h3>{image.archivedAt && <p>Archived {formatArchiveDate(image.archivedAt)}</p>}</div>{scope === 'active' ? <><div className="gallery-manager__card-actions"><button type="button" onClick={() => openEditForm(image)} className="gallery-manager__edit">Edit details</button><button type="button" onClick={() => setPendingAction({ image, action: 'archive' })} disabled={actionId === image._id} className="gallery-manager__archive">{actionId === image._id ? 'Working…' : 'Archive image'}</button></div><button type="button" className="gallery-manager__delete-path" onClick={() => chooseScope('archived')}>Need permanent delete? Open Archive <span aria-hidden="true">→</span></button></> : <div className="gallery-manager__card-actions"><button type="button" onClick={() => setPendingAction({ image, action: 'restore' })} disabled={actionId === image._id} className="gallery-manager__restore">{actionId === image._id ? 'Working…' : 'Restore image'}</button><button type="button" onClick={() => setPendingAction({ image, action: 'delete' })} disabled={actionId === image._id} className="gallery-manager__delete">Delete permanently</button></div>}</div></article>)}</div>}
    <ConfirmDialog open={Boolean(pendingAction)} title={dialog?.title || ''} message={dialog?.message || ''} confirmLabel={dialog?.label} busy={Boolean(actionId)} busyLabel={dialog?.busy} onCancel={() => setPendingAction(null)} onConfirm={() => void confirmAction()} />
  </div>;
}
