/* Gallery workspace: recoverable bulk media operations with search, filtering, and motion-safe feedback. */
import { useCallback, useEffect, useMemo, useState } from 'react';
import api from '../lib/api';
import ConfirmDialog from '../components/ConfirmDialog';
import ImageUploadField from '../components/ImageUploadField';
import '../styles/gallery-manager.css';

interface GalleryImage { _id: string; imageUrl: string; caption?: string; category: string; archivedAt?: string; }
type Scope = 'active' | 'archived'; type ArchiveAction = 'archive' | 'restore' | 'delete'; type PendingAction = { image: GalleryImage; action: ArchiveAction }; type BulkAction = 'archive' | 'restore';
const emptyForm = { imageUrl: '', caption: '', category: '' }; type GalleryFormErrors = Partial<Record<'imageUrl' | 'category', string>>;
function dialogCopy(action: ArchiveAction) { return action === 'archive' ? { title: 'Move image to Archive?', message: 'It will leave the public gallery but stay recoverable in Archive. You can restore it at any time.', label: 'Archive image', busy: 'Archiving…' } : action === 'restore' ? { title: 'Restore this gallery image?', message: 'The image will return to the active public gallery.', label: 'Restore image', busy: 'Restoring…' } : { title: 'Permanently delete this gallery image?', message: 'This archived image and its saved details will be permanently removed. This cannot be undone.', label: 'Delete permanently', busy: 'Deleting…' }; }
function bulkCopy(action: BulkAction, count: number) { return action === 'archive' ? { title: `Archive ${count} image${count === 1 ? '' : 's'}?`, message: 'The selected images will leave the public gallery and remain recoverable in Archive.', label: 'Archive selected', busy: 'Archiving…', notice: `${count} image${count === 1 ? '' : 's'} moved to Archive.` } : { title: `Restore ${count} image${count === 1 ? '' : 's'}?`, message: 'The selected images will return to the active public gallery.', label: 'Restore selected', busy: 'Restoring…', notice: `${count} image${count === 1 ? '' : 's'} restored to the active gallery.` }; }
function formatArchiveDate(value?: string) { return value ? new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Africa/Lagos' }).format(new Date(value)) : ''; }
function requestError(error: unknown, fallback: string) { return typeof error === 'object' && error !== null && 'response' in error ? (error as { response?: { data?: { error?: string } } }).response?.data?.error || fallback : fallback; }
function pause(duration: number) { return new Promise((resolve) => window.setTimeout(resolve, duration)); }

export default function GalleryManager() {
  const [scope, setScope] = useState<Scope>('active'); const [images, setImages] = useState<GalleryImage[]>([]); const [categories, setCategories] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState<string | null>(null); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [loadFailed, setLoadFailed] = useState(false); const [formErrors, setFormErrors] = useState<GalleryFormErrors>({}); const [pendingAction, setPendingAction] = useState<PendingAction | null>(null); const [pendingBulk, setPendingBulk] = useState<{ action: BulkAction; ids: string[] } | null>(null); const [actionId, setActionId] = useState<string | null>(null); const [bulkBusy, setBulkBusy] = useState(false); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [movingIds, setMovingIds] = useState<string[]>([]); const [searchInput, setSearchInput] = useState(''); const [query, setQuery] = useState(''); const [category, setCategory] = useState('all');
  const fetchImages = useCallback(async () => { setLoading(true); setLoadFailed(false); try { const res = await api.get('/api/gallery/admin', { params: { scope, ...(query ? { search: query } : {}), ...(category !== 'all' ? { category } : {}) } }); setImages(res.data.images); setCategories(res.data.categories || []); setSelectedIds([]); } catch (loadError) { setError(requestError(loadError, 'Could not load gallery images.')); setLoadFailed(true); } finally { setLoading(false); } }, [category, query, scope]);
  useEffect(() => { const timer = window.setTimeout(() => { void fetchImages(); }, 0); return () => window.clearTimeout(timer); }, [fetchImages]);
  useEffect(() => { if (!notice) return undefined; const timer = window.setTimeout(() => setNotice(''), 4200); return () => window.clearTimeout(timer); }, [notice]);
  function chooseScope(nextScope: Scope) { setScope(nextScope); setShowForm(false); setError(''); setSelectedIds([]); }
  function submitSearch(event: React.FormEvent) { event.preventDefault(); setQuery(searchInput.trim()); }
  function clearFilters() { setSearchInput(''); setQuery(''); setCategory('all'); }
  function openCreateForm() { setForm(emptyForm); setFormErrors({}); setEditingId(null); setShowForm(true); }
  function openEditForm(image: GalleryImage) { setForm({ imageUrl: image.imageUrl, caption: image.caption || '', category: image.category }); setFormErrors({}); setEditingId(image._id); setShowForm(true); }
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); const nextErrors: GalleryFormErrors = {}; if (!form.imageUrl.trim()) nextErrors.imageUrl = 'Upload an image before saving this gallery item.'; if (!form.category.trim()) nextErrors.category = 'Add a category so the gallery can be filtered.'; if (Object.keys(nextErrors).length) { setFormErrors(nextErrors); return; } setSaving(true); setError(''); setFormErrors({}); try { if (editingId) await api.put(`/api/gallery/${editingId}`, form); else await api.post('/api/gallery', form); setShowForm(false); setNotice(editingId ? 'Gallery image updated.' : 'Gallery image added to the active catalog.'); await fetchImages(); } catch (saveError) { setError(requestError(saveError, 'Something went wrong saving this image.')); } finally { setSaving(false); } }
  async function confirmAction() { if (!pendingAction) return; const { image, action } = pendingAction; setActionId(image._id); setError(''); try { if (action !== 'delete') setMovingIds([image._id]); await api[action === 'delete' ? 'delete' : 'post'](action === 'delete' ? `/api/gallery/${image._id}` : `/api/gallery/${image._id}/${action}`); if (action !== 'delete') await pause(220); setPendingAction(null); setNotice(action === 'archive' ? 'Image moved to Archive. You can restore it at any time.' : action === 'restore' ? 'Image restored to the active gallery.' : 'Archived image permanently deleted.'); await fetchImages(); } catch (actionError) { setMovingIds([]); setError(requestError(actionError, `Something went wrong ${action === 'delete' ? 'permanently deleting' : `${action}ing`} this image.`)); } finally { setActionId(null); setMovingIds([]); } }
  async function applyBulkAction() { if (!pendingBulk) return; const copy = bulkCopy(pendingBulk.action, pendingBulk.ids.length); setBulkBusy(true); setError(''); try { setMovingIds(pendingBulk.ids); const response = await api.post('/api/gallery/bulk-action', pendingBulk); const result = response.data as { affectedCount: number; skippedCount: number }; await pause(220); setPendingBulk(null); setNotice(result.skippedCount > 0 ? `${copy.notice} ${result.skippedCount} item${result.skippedCount === 1 ? '' : 's'} were already in that state.` : copy.notice); await fetchImages(); } catch (bulkError) { setMovingIds([]); setError(requestError(bulkError, 'Could not apply the bulk Gallery action.')); } finally { setBulkBusy(false); setMovingIds([]); } }
  const dialog = pendingAction ? dialogCopy(pendingAction.action) : null; const allVisibleSelected = images.length > 0 && images.every((image) => selectedIds.includes(image._id)); const selectedCount = selectedIds.length; const activeCopy = scope === 'active'; const selectedLabel = selectedCount === 1 ? '1 image selected' : `${selectedCount} images selected`;
  const visibleCategories = useMemo(() => categories.filter(Boolean), [categories]);
  return <div className="gallery-manager">
    <section className="gallery-manager__head"><div><div className="gallery-manager__eyebrow">Media library / gallery</div><h2>Gallery <em>control.</em></h2><p>{activeCopy ? 'Keep the public gallery intentional. Archive removes an image from view while keeping it recoverable.' : 'Review stored images here. Restore sends an image back to the public gallery; permanent deletion stays deliberately separate.'}</p></div>{activeCopy && <button type="button" onClick={openCreateForm} className="gallery-manager__add">Add image <span aria-hidden="true">+</span></button>}</section>
    <section className="gallery-manager__lifecycle" aria-label="Gallery image lifecycle"><div className="gallery-manager__lifecycle-copy"><span>{activeCopy ? 'Step 1 of 2' : 'Step 2 of 2'}</span><strong>{activeCopy ? 'Archive first. Delete only from Archive.' : 'Restore or permanently delete archived images.'}</strong><small>{activeCopy ? 'This protects your public gallery from accidental permanent loss.' : 'Permanent delete is irreversible and is always confirmed.'}</small></div><div className="gallery-manager__tabs" role="tablist" aria-label="Gallery catalog view"><button type="button" role="tab" aria-selected={scope === 'active'} onClick={() => chooseScope('active')} className={scope === 'active' ? 'is-active' : ''}>Active <span>Public</span></button><button type="button" role="tab" aria-selected={scope === 'archived'} onClick={() => chooseScope('archived')} className={scope === 'archived' ? 'is-active' : ''}>Archive <span>Restore / delete</span></button></div></section>
    <section className="gallery-manager__filters" aria-label="Search and filter gallery images"><form onSubmit={submitSearch}><label htmlFor="gallery-search">Search gallery</label><div><input id="gallery-search" value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder="Caption or category" /><button type="submit" className="gallery-manager__filter-submit">Search</button></div></form><label htmlFor="gallery-category-filter">Category<select id="gallery-category-filter" value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All categories</option>{visibleCategories.map((value) => <option value={value} key={value}>{value}</option>)}</select></label><button type="button" className="gallery-manager__clear-filters" onClick={clearFilters} disabled={!query && !searchInput && category === 'all'}>Clear filters</button></section>
    {error && <div className="gallery-manager__alert" role="alert"><span>{error}</span>{loadFailed && <button type="button" onClick={() => void fetchImages()}>Retry loading</button>}</div>}{notice && <div className="gallery-manager__toast" role="status">{notice}</div>}
    {showForm && <form onSubmit={handleSubmit} noValidate className="gallery-manager__form"><div><span>Image record</span><h3>{editingId ? 'Edit gallery image' : 'Add to public gallery'}</h3><p>Save the visual and its category together so the gallery stays easy to browse.</p></div><ImageUploadField value={form.imageUrl} onChange={(url) => setForm({ ...form, imageUrl: url })} />{formErrors.imageUrl && <p className="gallery-manager__field-error" role="alert">{formErrors.imageUrl}</p>}<div className="gallery-manager__form-grid"><label htmlFor="gallery-category">Category<input id="gallery-category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} placeholder="Plated, Events, Kitchen…" aria-invalid={Boolean(formErrors.category)} aria-describedby={formErrors.category ? 'gallery-category-error' : undefined} /></label><label htmlFor="gallery-caption">Caption <em>optional</em><input id="gallery-caption" value={form.caption} onChange={(e) => setForm({ ...form, caption: e.target.value })} placeholder="A concise public description" /></label></div>{formErrors.category && <p id="gallery-category-error" className="gallery-manager__field-error">{formErrors.category}</p>}<div className="gallery-manager__form-actions"><button type="submit" disabled={saving} className="gallery-manager__save">{saving ? 'Saving…' : editingId ? 'Save changes' : 'Save image'}</button><button type="button" onClick={() => setShowForm(false)} className="gallery-manager__cancel">Cancel</button></div></form>}
    <div className="gallery-manager__catalog-head"><div><span>{activeCopy ? 'Active gallery' : 'Archive bin'}</span><strong>{loading ? 'Loading images…' : `${images.length} ${images.length === 1 ? 'image' : 'images'}`}</strong></div>{activeCopy ? <p>To permanently remove an image, move it to Archive first.</p> : <p>Only archived images show the permanent Delete action.</p>}</div>
    {!loading && images.length > 0 && <section className="gallery-manager__bulk" aria-label="Bulk Gallery actions"><label><input type="checkbox" checked={allVisibleSelected} onChange={() => setSelectedIds(allVisibleSelected ? [] : images.map((image) => image._id))} aria-label="Select all visible gallery images" /> Select all visible</label><span>{selectedCount ? selectedLabel : 'Select images to manage several at once'}</span>{selectedCount > 0 && <div>{activeCopy ? <button type="button" onClick={() => setPendingBulk({ action: 'archive', ids: selectedIds })}>Archive selected</button> : <button type="button" onClick={() => setPendingBulk({ action: 'restore', ids: selectedIds })}>Restore selected</button>}</div>}</section>}
    {loading ? <div className="gallery-manager__empty">Loading gallery images…</div> : images.length === 0 ? <div className="gallery-manager__empty"><strong>{scope === 'archived' ? 'Your Archive is clear.' : 'No images match this view.'}</strong><span>{scope === 'archived' ? 'Archived images will appear here with Restore and permanent Delete controls.' : query || category !== 'all' ? 'Try another search or category, or clear the active filters.' : 'Use Add image to create a new public gallery record.'}</span>{activeCopy && !query && category === 'all' && <button type="button" onClick={openCreateForm}>Add image</button>}</div> : <div className="gallery-manager__grid">{images.map((image) => <article key={image._id} className="gallery-manager__card" data-moving={movingIds.includes(image._id)}><div className="gallery-manager__image-wrap"><img src={image.imageUrl} alt={image.caption || image.category} /><label className="gallery-manager__card-check"><input type="checkbox" checked={selectedIds.includes(image._id)} onChange={() => setSelectedIds((current) => current.includes(image._id) ? current.filter((id) => id !== image._id) : [...current, image._id])} aria-label={`Select ${image.caption || image.category}`} /></label><span>{image.category}</span>{scope === 'archived' && <b>Archived</b>}</div><div className="gallery-manager__card-body"><div className="gallery-manager__card-copy"><small>{image.category}</small><h3>{image.caption || 'Untitled gallery image'}</h3>{image.archivedAt && <p>Archived {formatArchiveDate(image.archivedAt)}</p>}</div>{scope === 'active' ? <><div className="gallery-manager__card-actions"><button type="button" onClick={() => openEditForm(image)} className="gallery-manager__edit">Edit details</button><button type="button" onClick={() => setPendingAction({ image, action: 'archive' })} disabled={actionId === image._id || bulkBusy} className="gallery-manager__archive">{actionId === image._id ? 'Working…' : 'Archive image'}</button></div><button type="button" className="gallery-manager__delete-path" onClick={() => chooseScope('archived')}>Need permanent delete? Open Archive <span aria-hidden="true">→</span></button></> : <div className="gallery-manager__card-actions"><button type="button" onClick={() => setPendingAction({ image, action: 'restore' })} disabled={actionId === image._id || bulkBusy} className="gallery-manager__restore">{actionId === image._id ? 'Working…' : 'Restore image'}</button><button type="button" onClick={() => setPendingAction({ image, action: 'delete' })} disabled={actionId === image._id || bulkBusy} className="gallery-manager__delete">Delete permanently</button></div>}</div></article>)}</div>}
    <ConfirmDialog open={Boolean(pendingAction)} title={dialog?.title || ''} message={dialog?.message || ''} confirmLabel={dialog?.label} busy={Boolean(actionId)} busyLabel={dialog?.busy} onCancel={() => setPendingAction(null)} onConfirm={() => void confirmAction()} />
    <ConfirmDialog open={Boolean(pendingBulk)} title={pendingBulk ? bulkCopy(pendingBulk.action, pendingBulk.ids.length).title : ''} message={pendingBulk ? bulkCopy(pendingBulk.action, pendingBulk.ids.length).message : ''} confirmLabel={pendingBulk ? bulkCopy(pendingBulk.action, pendingBulk.ids.length).label : ''} busy={bulkBusy} busyLabel={pendingBulk ? bulkCopy(pendingBulk.action, pendingBulk.ids.length).busy : 'Working…'} onCancel={() => { if (!bulkBusy) setPendingBulk(null); }} onConfirm={() => void applyBulkAction()} />
  </div>;
}
