/* Menu collection: general mobile-first catalog controls with image-forward cards, archive recovery, and action feedback. */
import { useCallback, useEffect, useState } from 'react';
import api from '../lib/api';
import ConfirmDialog from '../components/ConfirmDialog';
import ImageUploadField from '../components/ImageUploadField';
import '../styles/content-collection.css';

interface MenuItem { _id: string; name: string; description: string; category: string; image?: string; imageUrl?: string; featured: boolean; archivedAt?: string; }
type Scope = 'active' | 'archived'; type ArchiveAction = 'archive' | 'restore' | 'delete'; type PendingAction = { item: MenuItem; action: ArchiveAction };
const emptyForm = { name: '', description: '', category: '', image: '', featured: false }; type MenuFormErrors = Partial<Record<'name' | 'description' | 'category', string>>;
function dialogCopy(action: ArchiveAction, name: string) { if (action === 'archive') return { title: `Archive ${name}?`, message: 'This item will leave the public menu but remain recoverable in Archive.', label: 'Archive item', busy: 'Archiving…' }; if (action === 'restore') return { title: `Restore ${name}?`, message: 'This item will return to the active menu catalog and public menu.', label: 'Restore item', busy: 'Restoring…' }; return { title: `Permanently delete ${name}?`, message: 'This archived menu item will be permanently deleted and cannot be restored.', label: 'Delete permanently', busy: 'Deleting…' }; }
function formatDate(value?: string) { return value ? new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Africa/Lagos' }).format(new Date(value)) : ''; }
function message(error: unknown, fallback: string) { return typeof error === 'object' && error !== null && 'response' in error ? (error as { response?: { data?: { error?: string } } }).response?.data?.error || fallback : fallback; }

function MenuCardMedia({ item }: { item: MenuItem }) {
  const [failed, setFailed] = useState(false);
  const source = item.image || item.imageUrl;
  if (!source || failed) return <div className="collection-page__menu-media-fallback" aria-label={`No uploaded image for ${item.name}`}><span>{item.category}</span><strong>Image<br />pending</strong></div>;
  return <img src={source} alt={item.name} onError={() => setFailed(true)} />;
}

export default function MenuManager() {
  const [scope, setScope] = useState<Scope>('active'); const [items, setItems] = useState<MenuItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState<string | null>(null); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [loadFailed, setLoadFailed] = useState(false); const [formErrors, setFormErrors] = useState<MenuFormErrors>({}); const [pendingAction, setPendingAction] = useState<PendingAction | null>(null); const [actionId, setActionId] = useState<string | null>(null);
  const fetchItems = useCallback(async () => { setLoading(true); setLoadFailed(false); try { const res = await api.get('/api/menu/admin', { params: { scope } }); setItems(res.data.items); } catch (loadError) { setError(message(loadError, 'Could not load menu items.')); setLoadFailed(true); } finally { setLoading(false); } }, [scope]);
  useEffect(() => { const timer = window.setTimeout(() => { void fetchItems(); }, 0); return () => window.clearTimeout(timer); }, [fetchItems]);
  useEffect(() => { if (!notice) return undefined; const timer = window.setTimeout(() => setNotice(''), 3600); return () => window.clearTimeout(timer); }, [notice]);
  function chooseScope(nextScope: Scope) { setScope(nextScope); setShowForm(false); setError(''); }
  function openCreateForm() { setForm(emptyForm); setFormErrors({}); setEditingId(null); setShowForm(true); }
  function openEditForm(item: MenuItem) { setForm({ name: item.name, description: item.description, category: item.category, image: item.image || item.imageUrl || '', featured: item.featured }); setFormErrors({}); setEditingId(item._id); setShowForm(true); }
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); const nextErrors: MenuFormErrors = {}; if (!form.name.trim()) nextErrors.name = 'Add a name so visitors can identify this dish.'; if (!form.category.trim()) nextErrors.category = 'Add a category for menu navigation.'; if (!form.description.trim()) nextErrors.description = 'Add a short description for the menu card.'; if (Object.keys(nextErrors).length) { setFormErrors(nextErrors); return; } setSaving(true); setError(''); try { if (editingId) await api.put(`/api/menu/${editingId}`, form); else await api.post('/api/menu', form); setShowForm(false); setNotice(editingId ? 'Menu item updated.' : 'Menu item added to the active catalog.'); await fetchItems(); } catch (saveError) { setError(message(saveError, 'Something went wrong saving this item.')); } finally { setSaving(false); } }
  async function confirmAction() { if (!pendingAction) return; const { item, action } = pendingAction; setActionId(item._id); setError(''); try { if (action === 'delete') await api.delete(`/api/menu/${item._id}`); else await api.post(`/api/menu/${item._id}/${action}`); setPendingAction(null); setNotice(action === 'archive' ? 'Menu item moved to Archive.' : action === 'restore' ? 'Menu item restored to the active catalog.' : 'Archived menu item permanently deleted.'); await fetchItems(); } catch (actionError) { setError(message(actionError, `Something went wrong ${action === 'delete' ? 'permanently deleting' : `${action}ing`} this menu item.`)); } finally { setActionId(null); } }
  const dialog = pendingAction ? dialogCopy(pendingAction.action, pendingAction.item.name) : null; const active = scope === 'active';
  return <div className="collection-page" data-kind="menu"><section className="collection-page__head"><div><span>Content catalog / menu</span><h2>Menu <em>control.</em></h2><p>{active ? 'Give every dish a clear place in the public menu. Archive first to keep changes recoverable.' : 'Restore stored dishes or permanently delete only when a record is no longer needed.'}</p></div>{active && <button type="button" className="collection-page__add" onClick={openCreateForm}>Add item <span>+</span></button>}</section><section className="collection-page__lifecycle"><div><span>{active ? 'Active catalog' : 'Archive bin'}</span><strong>{active ? 'Archive first. Delete only from Archive.' : 'Restore or permanently delete archived items.'}</strong></div><div role="tablist" aria-label="Menu catalog view"><button type="button" role="tab" aria-selected={active} className={active ? 'is-active' : ''} onClick={() => chooseScope('active')}>Active menu</button><button type="button" role="tab" aria-selected={!active} className={!active ? 'is-active' : ''} onClick={() => chooseScope('archived')}>Archive</button></div></section>{error && <div className="collection-page__alert" role="alert"><span>{error}</span>{loadFailed && <button type="button" onClick={() => void fetchItems()}>Retry loading</button>}</div>}{notice && <div className="collection-page__notice" role="status">{notice}</div>}
    {showForm && <form onSubmit={handleSubmit} noValidate className="collection-page__form"><div><span>Menu record</span><h3>{editingId ? 'Edit menu item' : 'Add a menu item'}</h3></div><div className="collection-page__form-grid"><label htmlFor="menu-name">Dish name<input id="menu-name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="e.g. Chicken curry sauce" aria-invalid={Boolean(formErrors.name)} /></label><label htmlFor="menu-category">Category<input id="menu-category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} placeholder="e.g. Sauces" aria-invalid={Boolean(formErrors.category)} /></label></div>{(formErrors.name || formErrors.category) && <p className="collection-page__field-error">{formErrors.name || formErrors.category}</p>}<label htmlFor="menu-description">Public description<textarea id="menu-description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="A concise, appetising description" rows={4} aria-invalid={Boolean(formErrors.description)} /></label>{formErrors.description && <p className="collection-page__field-error">{formErrors.description}</p>}<ImageUploadField value={form.image} onChange={(url) => setForm({ ...form, image: url })} /><label className="collection-page__checkbox" htmlFor="menu-featured"><input id="menu-featured" type="checkbox" checked={form.featured} onChange={(e) => setForm({ ...form, featured: e.target.checked })} />Feature this dish on the homepage</label><div className="collection-page__form-actions"><button type="submit" disabled={saving}>{saving ? 'Saving…' : editingId ? 'Save changes' : 'Save menu item'}</button><button type="button" onClick={() => setShowForm(false)}>Cancel</button></div></form>}
    <div className="collection-page__catalog-head"><div><span>{active ? 'Active menu' : 'Archived menu'}</span><strong>{loading ? 'Loading items…' : `${items.length} ${items.length === 1 ? 'item' : 'items'}`}</strong></div><p>{active ? 'Select Archive to remove a dish from the public menu without losing it.' : 'Only archived records reveal the permanent Delete action.'}</p></div>{loading ? <div className="collection-page__empty">Loading menu items…</div> : items.length === 0 ? <div className="collection-page__empty"><strong>{active ? 'Your menu is ready for a first item.' : 'Your Menu Archive is clear.'}</strong><span>{active ? 'Add a dish to start building the public menu.' : 'Archived items appear here with Restore and permanent Delete controls.'}</span></div> : <div className="collection-page__cards">{items.map((item) => <article key={item._id} className="collection-page__card collection-page__card--media"><figure className="collection-page__menu-media"><MenuCardMedia item={item} />{item.featured && <figcaption>Featured</figcaption>}</figure><div className="collection-page__card-main"><div className="collection-page__card-meta"><span>{item.category}</span>{item.featured && <b>Featured</b>}</div><h3>{item.name}</h3><p>{item.description}</p>{item.archivedAt && <small>Archived {formatDate(item.archivedAt)}</small>}</div><div className="collection-page__card-actions">{active ? <><button type="button" onClick={() => openEditForm(item)}>Edit details</button><button type="button" className="collection-page__primary" onClick={() => setPendingAction({ item, action: 'archive' })} disabled={actionId === item._id}>{actionId === item._id ? 'Working…' : 'Archive item'}</button></> : <><button type="button" className="collection-page__primary" onClick={() => setPendingAction({ item, action: 'restore' })} disabled={actionId === item._id}>{actionId === item._id ? 'Working…' : 'Restore item'}</button><button type="button" className="collection-page__danger" onClick={() => setPendingAction({ item, action: 'delete' })} disabled={actionId === item._id}>Delete permanently</button></>}</div></article>)}</div>}<ConfirmDialog open={Boolean(pendingAction)} title={dialog?.title || ''} message={dialog?.message || ''} confirmLabel={dialog?.label} busy={Boolean(actionId)} busyLabel={dialog?.busy} onCancel={() => setPendingAction(null)} onConfirm={() => void confirmAction()} /></div>;
}
