/* Testimonials collection: shared content-management mobile hierarchy, safety lifecycle, and visible feedback. */
import { useCallback, useEffect, useState } from 'react';
import api from '../lib/api';
import ConfirmDialog from '../components/ConfirmDialog';
import '../styles/content-collection.css';

interface Testimonial { _id: string; clientName: string; quote: string; eventType?: string; featured: boolean; archivedAt?: string; }
type Scope = 'active' | 'archived'; type ArchiveAction = 'archive' | 'restore' | 'delete'; type PendingAction = { testimonial: Testimonial; action: ArchiveAction };
const emptyForm = { clientName: '', quote: '', eventType: '', featured: false }; type TestimonialFormErrors = Partial<Record<'clientName' | 'quote', string>>;
function dialogCopy(action: ArchiveAction, name: string) { return action === 'archive' ? { title: `Archive ${name}?`, message: 'This testimonial will leave public content but remain recoverable in Archive.', label: 'Archive testimonial', busy: 'Archiving…' } : action === 'restore' ? { title: `Restore ${name}?`, message: 'This testimonial will return to active public content.', label: 'Restore testimonial', busy: 'Restoring…' } : { title: `Permanently delete ${name}?`, message: 'This archived testimonial will be permanently deleted and cannot be restored.', label: 'Delete permanently', busy: 'Deleting…' }; }
function formatDate(value?: string) { return value ? new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Africa/Lagos' }).format(new Date(value)) : ''; }
function message(error: unknown, fallback: string) { return typeof error === 'object' && error !== null && 'response' in error ? (error as { response?: { data?: { error?: string } } }).response?.data?.error || fallback : fallback; }

export default function TestimonialsManager() {
  const [scope, setScope] = useState<Scope>('active'); const [testimonials, setTestimonials] = useState<Testimonial[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState<string | null>(null); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [loadFailed, setLoadFailed] = useState(false); const [formErrors, setFormErrors] = useState<TestimonialFormErrors>({}); const [pendingAction, setPendingAction] = useState<PendingAction | null>(null); const [actionId, setActionId] = useState<string | null>(null);
  const fetchTestimonials = useCallback(async () => { setLoading(true); setLoadFailed(false); try { const res = await api.get('/api/testimonials/admin', { params: { scope } }); setTestimonials(res.data.testimonials); } catch (loadError) { setError(message(loadError, 'Could not load testimonials.')); setLoadFailed(true); } finally { setLoading(false); } }, [scope]);
  useEffect(() => { const timer = window.setTimeout(() => { void fetchTestimonials(); }, 0); return () => window.clearTimeout(timer); }, [fetchTestimonials]);
  useEffect(() => { if (!notice) return undefined; const timer = window.setTimeout(() => setNotice(''), 3600); return () => window.clearTimeout(timer); }, [notice]);
  function chooseScope(nextScope: Scope) { setScope(nextScope); setShowForm(false); setError(''); }
  function openCreateForm() { setForm(emptyForm); setFormErrors({}); setEditingId(null); setShowForm(true); }
  function openEditForm(item: Testimonial) { setForm({ clientName: item.clientName, quote: item.quote, eventType: item.eventType || '', featured: item.featured }); setFormErrors({}); setEditingId(item._id); setShowForm(true); }
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); const nextErrors: TestimonialFormErrors = {}; if (!form.clientName.trim()) nextErrors.clientName = 'Add the client name for this testimonial.'; if (!form.quote.trim()) nextErrors.quote = 'Add the approved testimonial copy before saving.'; if (Object.keys(nextErrors).length) { setFormErrors(nextErrors); return; } setSaving(true); setError(''); try { if (editingId) await api.put(`/api/testimonials/${editingId}`, form); else await api.post('/api/testimonials', form); setShowForm(false); setNotice(editingId ? 'Testimonial updated.' : 'Testimonial added to the active catalog.'); await fetchTestimonials(); } catch (saveError) { setError(message(saveError, 'Something went wrong saving this testimonial.')); } finally { setSaving(false); } }
  async function confirmAction() { if (!pendingAction) return; const { testimonial, action } = pendingAction; setActionId(testimonial._id); setError(''); try { if (action === 'delete') await api.delete(`/api/testimonials/${testimonial._id}`); else await api.post(`/api/testimonials/${testimonial._id}/${action}`); setPendingAction(null); setNotice(action === 'archive' ? 'Testimonial moved to Archive.' : action === 'restore' ? 'Testimonial restored to the active catalog.' : 'Archived testimonial permanently deleted.'); await fetchTestimonials(); } catch (actionError) { setError(message(actionError, `Something went wrong ${action === 'delete' ? 'permanently deleting' : `${action}ing`} this testimonial.`)); } finally { setActionId(null); } }
  const dialog = pendingAction ? dialogCopy(pendingAction.action, pendingAction.testimonial.clientName) : null; const active = scope === 'active';
  return <div className="collection-page" data-kind="testimonials"><section className="collection-page__head"><div><span>Content catalog / testimonials</span><h2>Testimonials <em>control.</em></h2><p>{active ? 'Keep approved social proof intentional. Archive a quote first so your catalog stays recoverable.' : 'Restore approved quotes or permanently delete only when the record is no longer needed.'}</p></div>{active && <button type="button" className="collection-page__add" onClick={openCreateForm}>Add testimonial <span>+</span></button>}</section><section className="collection-page__lifecycle"><div><span>{active ? 'Active catalog' : 'Archive bin'}</span><strong>{active ? 'Archive first. Delete only from Archive.' : 'Restore or permanently delete archived testimonials.'}</strong></div><div role="tablist" aria-label="Testimonial catalog view"><button type="button" role="tab" aria-selected={active} className={active ? 'is-active' : ''} onClick={() => chooseScope('active')}>Active testimonials</button><button type="button" role="tab" aria-selected={!active} className={!active ? 'is-active' : ''} onClick={() => chooseScope('archived')}>Archive</button></div></section>{error && <div className="collection-page__alert" role="alert"><span>{error}</span>{loadFailed && <button type="button" onClick={() => void fetchTestimonials()}>Retry loading</button>}</div>}{notice && <div className="collection-page__notice" role="status">{notice}</div>}
    {showForm && <form onSubmit={handleSubmit} noValidate className="collection-page__form"><div><span>Testimonial record</span><h3>{editingId ? 'Edit testimonial' : 'Add an approved quote'}</h3></div><div className="collection-page__form-grid"><label htmlFor="testimonial-client">Client name<input id="testimonial-client" value={form.clientName} onChange={(e) => setForm({ ...form, clientName: e.target.value })} placeholder="Client or organisation" aria-invalid={Boolean(formErrors.clientName)} /></label><label htmlFor="testimonial-event">Event type <em>optional</em><input id="testimonial-event" value={form.eventType} onChange={(e) => setForm({ ...form, eventType: e.target.value })} placeholder="e.g. Private dinner" /></label></div>{formErrors.clientName && <p className="collection-page__field-error">{formErrors.clientName}</p>}<label htmlFor="testimonial-quote">Approved quote<textarea id="testimonial-quote" value={form.quote} onChange={(e) => setForm({ ...form, quote: e.target.value })} placeholder="The approved public testimonial" rows={5} aria-invalid={Boolean(formErrors.quote)} /></label>{formErrors.quote && <p className="collection-page__field-error">{formErrors.quote}</p>}<label className="collection-page__checkbox" htmlFor="testimonial-featured"><input id="testimonial-featured" type="checkbox" checked={form.featured} onChange={(e) => setForm({ ...form, featured: e.target.checked })} />Feature this testimonial on the homepage</label><div className="collection-page__form-actions"><button type="submit" disabled={saving}>{saving ? 'Saving…' : editingId ? 'Save changes' : 'Save testimonial'}</button><button type="button" onClick={() => setShowForm(false)}>Cancel</button></div></form>}
    <div className="collection-page__catalog-head"><div><span>{active ? 'Active testimonials' : 'Archived testimonials'}</span><strong>{loading ? 'Loading testimonials…' : `${testimonials.length} ${testimonials.length === 1 ? 'testimonial' : 'testimonials'}`}</strong></div><p>{active ? 'Archive a quote to remove it from public content while keeping it recoverable.' : 'Only archived testimonials reveal the permanent Delete action.'}</p></div>{loading ? <div className="collection-page__empty">Loading testimonials…</div> : testimonials.length === 0 ? <div className="collection-page__empty"><strong>{active ? 'Your testimonial catalog is ready.' : 'Your Testimonial Archive is clear.'}</strong><span>{active ? 'Add an approved quote when you are ready.' : 'Archived testimonials appear here with Restore and permanent Delete controls.'}</span></div> : <div className="collection-page__cards">{testimonials.map((item) => <article key={item._id} className="collection-page__card"><div className="collection-page__card-main"><div className="collection-page__card-meta"><span>{item.eventType || 'Client quote'}</span>{item.featured && <b>Featured</b>}</div><h3>{item.clientName}</h3><p>&ldquo;{item.quote}&rdquo;</p>{item.archivedAt && <small>Archived {formatDate(item.archivedAt)}</small>}</div><div className="collection-page__card-actions">{active ? <><button type="button" onClick={() => openEditForm(item)}>Edit details</button><button type="button" className="collection-page__primary" onClick={() => setPendingAction({ testimonial: item, action: 'archive' })} disabled={actionId === item._id}>{actionId === item._id ? 'Working…' : 'Archive testimonial'}</button></> : <><button type="button" className="collection-page__primary" onClick={() => setPendingAction({ testimonial: item, action: 'restore' })} disabled={actionId === item._id}>{actionId === item._id ? 'Working…' : 'Restore testimonial'}</button><button type="button" className="collection-page__danger" onClick={() => setPendingAction({ testimonial: item, action: 'delete' })} disabled={actionId === item._id}>Delete permanently</button></>}</div></article>)}</div>}<ConfirmDialog open={Boolean(pendingAction)} title={dialog?.title || ''} message={dialog?.message || ''} confirmLabel={dialog?.label} busy={Boolean(actionId)} busyLabel={dialog?.busy} onCancel={() => setPendingAction(null)} onConfirm={() => void confirmAction()} /></div>;
}
